### ISSUE TITLE
Improvement to disable backlight

### ISSUE THREAD

**Issue by MrTux86** [davidgmccall/kiosk_raspberry_pi_bookworm_wayland_blank_screen#1]
First I want to say: Thank you!
I tried a lot of solutions to blank my raspi display.
Your way was the first to really do what I wanted :)
The only downside is, that the backlight stays on when the screen goes blank.

May I suggest, that you add the following lines to "blank_screen.bash"

        sudo sh -c 'echo "1" > /sys/class/backlight/rpi_backlight/bl_power' #(turn backlight off)

and

        sudo sh -c 'echo "0" > /sys/class/backlight/rpi_backlight/bl_power' #(turn backlight on)

something like this:
```
    if [[ $isBlank == 0 && ${keysLog} -ot ${keysTime} ]] ; then
        pqiv --fullscreen --hide-info-box --fade ${blankImage} &
        blankPid=$!
        isBlank=1
-->     sudo sh -c 'echo "1" > /sys/class/backlight/rpi_backlight/bl_power'
    elif [[ $isBlank == 1 && ${keysLog} -nt ${keysTime} ]] ; then
        if [[ ${blankPid} ]] ; then
            kill ${blankPid}
-->         sudo sh -c 'echo "0" > /sys/class/backlight/rpi_backlight/bl_power'
            blankPid=
        fi
        isBlank=0
```

I got the additional information from this site:

[Raspi Forum](https://forums.raspberrypi.com/viewtopic.php?t=209778)

It seems like the location differs from device to device (my Raspi 4 was missing the "rpi_backlight" directory. Instead there was a symlink to another directory which contained the "bl_power" file).

Edit:

Turning off the backlight will only make sense if you're using an attached display (like the official 7" raspi display)

**Comment by davidgmccall** [comment]
Thanks, I've added your suggestions.
